In [6]:
import numpy as np

1.	Array Creation

Create a 1D array of numbers from 10 to 50.

In [13]:
arr=np.arange(10,51) 
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Create a 3x3 array of random numbers between 0 and 1.

In [14]:
arr1 = np.random.rand(3, 3)
print(arr1)

[[0.96098184 0.57105567 0.87893671]
 [0.70010253 0.07753503 0.24459898]
 [0.48106723 0.29944312 0.90718749]]


Find the shape, size, and data type of the array you created in the previous task.

In [15]:
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

(3, 3)
9
float64


3.	Basic Operations


Add 5 to every element of a 1D array.

In [16]:
arr=np.array([2,4,6,8])
print(arr+5)

[ 7  9 11 13]


Multiply two 2D arrays element-wise.

In [17]:
arr=np.array([[1,2,3],[3,4,5],[1,5,9]])
arr1=np.array([[3,4,6],[5,6,8],[2,5,7]])
print(arr*arr1)

[[ 3  8 18]
 [15 24 40]
 [ 2 25 63]]


Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.


In [27]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr)
print(arr[0,:])
print(arr[:,-1])
print(arr[:3, :2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


Create a 10-element array of random integers between 1 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.


In [29]:
a = np.random.randint(1, 101, 10)
print(a)
print(a.max())
print(a.min())
print(a.mean())
print(a.std())

[ 38  35 100  20  42  23  85 100   8  92]
100
8
54.3
34.10293242523288


Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.

In [30]:
arr = np.arange(1, 13)
matrix= arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.

In [34]:
arr=np.ones([3,3])
a=np.array([1,2,3])
print(arr)
print(arr+a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.

In [37]:
arr= np.random.randint(1, 51, 10)
ele = arr[arr % 5 == 0]
print(arr)
print(ele)

[31 23  2 23 31 33 26 15 43  3]
[15]


Create two 2x2 matrices and perform matrix multiplication.

In [38]:
mat1= np.array([[2,4], [6, 8]])
mat2 = np.array([[1, 5], [7, 9]])
print(np.dot(mat1, mat2))

[[ 30  46]
 [ 62 102]]


Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [39]:
arr= np.arange(1, 17).reshape(4, 4)
dia = arr[np.diag_indices(4)]
print(arr)
print(dia)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
